# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Booked', 'Booked')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Booked', 'Booked')], default=' ', max_length=50),
        ),
    ]
