# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 21:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0013_auto_20170328_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='physiotherapist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtestdata',
            name='test_type',
            field=models.CharField(choices=[('--Lab Test--', ''), ('Complete Blood Count', 'Complete Blood Count'), ('Fast Blood Sugar', 'Fast Blood Sugar'), ('Postprandial Blood Sugar', 'Postprandial Blood Sugar'), ('Lipid Profile', 'Lipid Profile'), ('Uric Acid', 'Uric Acid'), ('Blood Pressure Test', 'Blood Pressure Test'), ('--Vaccination--', ''), ('H1N1', 'H1N1'), ('Chicken Pox', 'Chicken Pox'), ('Typhoid', 'Typhoid'), ('Hepatitis B', 'Hepatitis B'), ('Pneumonia', 'Pneumonia')], default='', max_length=30),
        ),
    ]
