# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_auto_20170328_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestdata',
            name='contact_number',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
