# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_labtestdata_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='duration',
            field=models.CharField(choices=[('', '--Choose--'), ('8hrs', '8hrs/day'), ('12hrs', '12hrs/day'), ('16hrs', '16hrs/day'), ('24hrs', '24hrs/day')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='period',
            field=models.CharField(choices=[('', '--Choose--'), ('1day', '1day'), ('7day', '7days'), ('15day', '15days'), ('30day', '30days')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='service_required',
            field=models.CharField(choices=[('', '--Choose--'), ('MALE NURSE', 'Male Nurse'), ('FEMALE NURSE', 'Female Nurse'), ('BABY SITTER', 'Babysitter')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtestdata',
            name='test_type',
            field=models.CharField(choices=[('', '--Lab Test--'), ('Complete Blood Count', 'Complete Blood Count'), ('Fast Blood Sugar', 'Fast Blood Sugar'), ('Postprandial Blood Sugar', 'Postprandial Blood Sugar'), ('Lipid Profile', 'Lipid Profile'), ('Uric Acid', 'Uric Acid'), ('Blood Pressure Test', 'Blood Pressure Test'), ('', '--Vaccination--'), ('H1N1', 'H1N1'), ('Chicken Pox', 'Chicken Pox'), ('Typhoid', 'Typhoid'), ('Hepatitis B', 'Hepatitis B'), ('Pneumonia', 'Pneumonia')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='duration',
            field=models.CharField(choices=[('', '--Choose--'), ('8hrs', '8hrs/day'), ('12hrs', '12hrs/day'), ('16hrs', '16hrs/day'), ('24hrs', '24hrs/day')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='period',
            field=models.CharField(choices=[('', '--Choose--'), ('1day', '1day'), ('7day', '7days'), ('15day', '15days'), ('30day', '30days')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='service_required',
            field=models.CharField(choices=[('', '--Choose--'), ('MN', 'Male Nurse'), ('FN', 'Female Nurse'), ('BS', 'Babysitter'), ('PT', 'Physiotherapist')], default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='period',
            field=models.CharField(choices=[('', '--Choose--'), ('1day', '1day'), ('7day', '7days'), ('15day', '15days'), ('30day', '30days')], default='', max_length=20),
        ),
    ]
