# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_auto_20170328_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptiondata',
            name='buy',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
