# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_auto_20170329_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Staff', 'Staff')], default='Patient', max_length=20),
        ),
    ]
