# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 12:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_auto_20170329_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='duration',
            field=models.IntegerField(default=15, help_text='value 2 to 30', validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='phone_number',
            field=models.IntegerField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='phone_number',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
