# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_auto_20170423_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='duration',
            field=models.IntegerField(default=15, help_text='value 2 to 30'),
        ),
    ]
