# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_auto_20170423_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='duration',
            field=models.CharField(choices=[('', '--Choose--'), ('8hrs', '8hrs/day'), ('12hrs', '12hrs/day'), ('16hrs', '16hrs/day'), ('24hrs', '24hrs/day')], default='', max_length=20),
        ),
    ]
