# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_auto_20170423_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='physiotherapist',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
