# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_auto_20170423_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physiotherapist',
            name='phone_number',
            field=models.IntegerField(default=None),
        ),
    ]
