# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 19:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_auto_20170423_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='duration',
            field=models.PositiveIntegerField(default=13, help_text='value 2 to 24', validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(2)]),
        ),
    ]
