# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 20:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0034_auto_20170424_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='period',
            field=models.PositiveIntegerField(default=16, help_text='value 1 to 30', validators=[django.core.validators.MaxValueValidator(30), django.core.validators.MinValueValidator(1)]),
        ),
    ]
