# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_auto_20170424_0216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Physiotherapist',
            new_name='PhysiotherapistDetail',
        ),
    ]
