# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0036_auto_20170424_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='labtestdata',
            name='contact_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='packagedata',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='physiotherapistdetail',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
